export const upcomingTrips = [
  {
    id: 1,
    destination: "Phuket, Thailand",
    type: "Flight + Hotel",
    dates: "Dec 15 - Dec 22, 2025",
    bookingRef: "FB-2025-001234",
    status: "confirmed",
    price: "$649",
    details: {
      flight: "JFK → HKT",
      hotel: "Paradise Beach Resort",
      guests: "2 Adults",
    },
  },
  {
    id: 2,
    destination: "Tokyo, Japan",
    type: "Flight Only",
    dates: "Jan 10 - Jan 20, 2026",
    bookingRef: "FB-2026-001567",
    status: "confirmed",
    price: "$1,099",
    details: {
      flight: "LAX → NRT",
      guests: "1 Adult",
    },
  },
];

// Enhanced booking history with flights, hotels, and cars
export const bookingHistory = [
  {
    id: 3,
    destination: "Paris, France",
    type: "Flight",
    category: "flight",
    dates: "Aug 5 - Aug 12, 2025",
    bookingRef: "FB-2025-000987",
    status: "completed",
    price: "$899",
    details: {
      flight: "JFK → CDG",
      guests: "2 Adults",
    },
  },
  {
    id: 4,
    destination: "Barcelona, Spain",
    type: "Hotel",
    category: "hotel",
    dates: "Jun 20 - Jun 27, 2025",
    bookingRef: "FB-2025-000654",
    status: "completed",
    price: "$799",
    details: {
      hotel: "Gothic Quarter Hotel",
      guests: "2 Adults",
      nights: "7 nights",
    },
  },
  {
    id: 5,
    destination: "Miami, Florida",
    type: "Car Rental",
    category: "car",
    dates: "Jul 15 - Jul 22, 2025",
    bookingRef: "FB-2025-000543",
    status: "completed",
    price: "$289",
    details: {
      car: "Toyota Camry or similar",
      pickUp: "Miami International Airport",
      dropOff: "Miami International Airport",
      days: "7 days",
    },
  },
  {
    id: 6,
    destination: "Dubai, UAE",
    type: "Hotel",
    category: "hotel",
    dates: "May 10 - May 17, 2025",
    bookingRef: "FB-2025-000432",
    status: "completed",
    price: "$1,299",
    details: {
      hotel: "Burj Al Arab",
      guests: "2 Adults",
      nights: "7 nights",
    },
  },
  {
    id: 7,
    destination: "Los Angeles, CA",
    type: "Car Rental",
    category: "car",
    dates: "Apr 5 - Apr 12, 2025",
    bookingRef: "FB-2025-000321",
    status: "completed",
    price: "$349",
    details: {
      car: "Ford Mustang Convertible",
      pickUp: "LAX Airport",
      dropOff: "LAX Airport",
      days: "7 days",
    },
  },
  {
    id: 8,
    destination: "London, UK",
    type: "Flight",
    category: "flight",
    dates: "Mar 20 - Mar 28, 2025",
    bookingRef: "FB-2025-000210",
    status: "completed",
    price: "$649",
    details: {
      flight: "JFK → LHR",
      guests: "1 Adult",
    },
  },
  {
    id: 9,
    destination: "Rome, Italy",
    type: "Hotel",
    category: "hotel",
    dates: "Feb 14 - Feb 21, 2025",
    bookingRef: "FB-2025-000109",
    status: "completed",
    price: "$899",
    details: {
      hotel: "Hotel de Russie",
      guests: "2 Adults",
      nights: "7 nights",
    },
  },
  {
    id: 10,
    destination: "San Francisco, CA",
    type: "Car Rental",
    category: "car",
    dates: "Jan 8 - Jan 15, 2025",
    bookingRef: "FB-2025-000087",
    status: "completed",
    price: "$259",
    details: {
      car: "Tesla Model 3",
      pickUp: "SFO Airport",
      dropOff: "SFO Airport",
      days: "7 days",
    },
  },
];
